src/recipe_project/urls.py
# In this file you’ll specify the routes to your apps. As you create apps, you’ll
# have your own urls.py files that you’ll connect to this file. Imagine this file as the table of contents of your site.


from django.contrib import admin
from django.urls import path, include
from django.conf import settings
from django.conf.urls.static import static
from .views import home, login_view, logout_view

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', home, name = 'home'),
    path('', include('recipes.urls')),
    path('login/', login_view, name = 'login'),
    path('logout/', logout_view, name = 'logout'),
]

urlpatterns += static(settings.MEDIA_URL, document_root = settings.MEDIA_ROOT)

src/recipes/urls.py
from django.urls import path
from .views import RecipeListView, RecipeDetailView, get_queryset, add_recipe, update_recipe, delete_recipe, about_page

app_name = 'recipes'

## Maps the '' address to the home function-based view
urlpatterns = [
  path('about', about_page, name='about'),
  path('recipes/', RecipeListView.as_view(), name='list'),
  path('recipes/search', get_queryset, name='search'),
  path('recipes/add', add_recipe, name='add'),
  path('recipes/<pk>', RecipeDetailView.as_view(), name='detail'),
  path('recipes/update/<pk>', update_recipe, name='update'),
  path('recipes/delete/<pk>', delete_recipe, name='delete'),
]

src/recipes/models.py
from django.db import models
from django.shortcuts import reverse

# Create your models here.

class Recipe(models.Model):
    name = models.CharField(max_length=50)
    ingredients = models.CharField(
        max_length=225, help_text="Enter the ingredients, separated by a comma"
    )
    cooking_time = models.IntegerField(help_text="Enter cooking time in minutes")
    difficulty = models.CharField(max_length=20, blank=True)
    pic = models.ImageField(upload_to="recipes", default="no_picture")

    def __str__(self):
        return self.name
    
    def get_absolute_url(self):
        return reverse ("recipes:detail", kwargs={"pk": self.pk})
    
    def return_ingredients_as_list(self):
        return self.ingredients.split(",")
    
    def calculate_difficulty(self):
        num_ingredients = len(self.return_ingredients_as_list())
        if self.cooking_time < 10 and num_ingredients < 4:
            return "Easy"
        elif self.cooking_time < 10 and num_ingredients >= 4:
            return "Medium"
        elif self.cooking_time >= 10 and num_ingredients < 4:
            return "Intermediate"
        elif self.cooking_time >= 10 and num_ingredients >= 4:
            return "Hard"
        
    def save(self, *args, **kwargs):
        self.difficulty = self.calculate_difficulty()
        super().save(*args, **kwargs)

src/recipes/forms.py
from django import forms
from .models import Recipe

CHART_CHOICES = {
  ('#1', 'Bar Chart'),
  ('#2', 'Pie Chart'),
  ('#3', 'Line Chart')
}

class RecipeSearchForm(forms.Form):
  recipe_search = forms.CharField(max_length=120, label='Enter Recipe / Ingredient', required=False)
  chart_type = forms.ChoiceField(choices=CHART_CHOICES, label='Choose a Chart Type')

class RecipeForm(forms.ModelForm):
  class Meta:
    model = Recipe
    fields = ['name', 'cooking_time', 'ingredients', 'pic']
    widgets = {
      'ingredients': forms.Textarea(attrs={'rows':4, 'cols':25}),
      }

src/recipe_project/views.py
from django.shortcuts import render, redirect
from django.contrib.auth import authenticate, login, logout
from django.contrib.auth.forms import AuthenticationForm

def home(request):
  return redirect('login')

def login_view(request):
  error_message = None
  form = AuthenticationForm()

  if request.method == 'POST':
    form = AuthenticationForm(data = request.POST)
    if form.is_valid():
      username = form.cleaned_data.get('username')
      password = form.cleaned_data.get('password')
      user = authenticate(username = username, password = password)
      if user is not None:
        login(request, user)
        return redirect('recipes:list')
    else:
      error_message = 'oops... something went wrong'
  context = {
    'form': form,
    'error_message': error_message
  }

  return render(request, 'auth/home.html', context)

def logout_view(request):
  logout(request)
  return render(request, 'auth/success.html')

src/recipes/views.py
from django.shortcuts import render, redirect, get_object_or_404
from django.db.models import Q
from django.contrib import messages
from django.contrib.auth.mixins import LoginRequiredMixin
from django.contrib.auth.decorators import login_required
from django.views.generic import ListView, DetailView
from .forms import RecipeSearchForm, RecipeForm
from .models import Recipe
from .utils import get_chart

import pandas as pd

# Create your views here.
@login_required
def get_queryset(request):
    form = RecipeSearchForm(request.POST or None)
    # Initialize dataframe
    recipes_df = None
    qs = None
    chart = None

    if request.method == 'POST':
      recipe_search = request.POST.get('recipe_search')
      chart_type = request.POST.get('chart_type')

      qs = Recipe.objects.filter(
          Q(name__icontains=recipe_search) |
          Q(ingredients__icontains=recipe_search) |
          Q(name=recipe_search)
        )

      if qs:
        recipes_df = pd.DataFrame(qs.values())

        chart = get_chart(chart_type, recipes_df, recipe_search)

        #convert the dataframe to HTML
        recipes_df=recipes_df.to_html()

      else:
        qs = 'No recipes found'

    context = {
      'form': form,
      'recipes_df': recipes_df,
      'qs': qs,
      'chart': chart}

    return render(request, 'recipes/recipe_search.html', context)

@login_required
def add_recipe(request):
  if request.method == 'POST':
    form = RecipeForm(request.POST, request.FILES)

    if form.is_valid():
      form.save()
      messages.info(request, 'Recipe added successfully!')
      return redirect('recipes:list')
  else:
    form = RecipeForm()

  return render(request, 'recipes/add_recipe.html', {'form': form})
@login_required
def update_recipe(request, pk):
    # Retrieve the recipe or return a 404 if not found
    recipe = get_object_or_404(Recipe, pk=pk)
    if request.method == 'POST':
        form = RecipeForm(request.POST, request.FILES, instance=recipe)
        if form.is_valid():
            form.save()
            messages.info(request, 'Recipe updated successfully!')
            return redirect('recipes:detail', recipe.pk)
    else:
        # If not a POST request, instantiate the form with the existing recipe
        form = RecipeForm(instance=recipe)
    # Render the template with the form and recipe instance
    return render(request, 'recipes/recipe_detail.html', {'form': form, 'object': recipe})
@login_required
def delete_recipe(request, pk):
  recipe = get_object_or_404(Recipe, pk=pk)
  recipe.delete()
  messages.info(request, 'Recipe deleted successfully!')
  return redirect('recipes:list')

@login_required
def about_page(request):
  return render(request, 'recipes/about.html')

class RecipeListView(LoginRequiredMixin, ListView):
  model = Recipe
  template_name = 'recipes/recipe_list.html'


class RecipeDetailView(LoginRequiredMixin, DetailView):
  model = Recipe
  template_name = 'recipes/recipe_detail.html'

  def get_context_data(self, **kwargs):
      context = super().get_context_data(**kwargs) # Adds extra information to the context passed to the template.
      
      recipe = self.get_object() # Retrieves the specific Recipe object being viewed.
      context['form'] = RecipeForm(instance=recipe)  # Adds a form populated with the recipe's data to the context.
      return context

src/recipes/templates/recipes/about.html
{% load static %}

<!DOCTYPE html>
<html lang="en">

<head>
  <meta charset="UTF-8">
  <meta name="viewport" content="width=device-width, initial-scale=1.0">
  <link rel="stylesheet" type="text/css" href="{% static 'recipes/css/search.css' %}">
  <title>Document</title>
</head>

<body>
  <h1><a href="{% url 'recipes:list' %}">About</a></h1>
  <br>
  <div class="navigation">
    <button onclick="showMenu()" class="navigation">
      <img src="{% static 'recipes/images/recipe.jpg' %}" width="26px" />
    </button>
    <div id="nav" class="hide">
      <ul>
        <a href="{% url 'recipes:list' %}">
          <li>home</li>
        </a>
        <a href="{% url 'recipes:search' %}">
          <li>search</li>
        </a>
        <a href="{% url 'recipes:add' %}">
          <li>add recipe</li>
        </a>
        <a href="{% url 'logout' %}">
          <li>logout</li>
        </a>
      </ul>
    </div>
  </div>
  <div class="about_card">
    <div class="about_info">
      Hello! I'm Rebekah Willis, a full-stack developer who
      <br>is passionate about building interactive web applications
      <br> in Java Script and Python.
      <br><br>
      Interested in seeing more of my work?
      <br><br>
      <a href="https://github.com/rbkh17willis" target="_blank">
        <button>portfolio</button>
      </a>
    </div>
    <br><br>
    <div class="about_table">
      <table cellpadding="0" cellspacing="0">
        <tr>
          <th>
            <span style="border-bottom: 1px dotted  black;">contact me</span>
          </th>
          <th>
            <span style="border-bottom: 1px dotted  black;">find me on</span>
          </th>
        </tr>
        <tr>
          <td>&nbsp;</td>
        </tr>
        <tr>
          <td><a href="mailto:rbkh17willis@gmail.com">email</a></td>
          <td>
            <a href="https://github.com/rbkh17willis" target="_blank">github</a>
          </td>
        </tr>
        <tr>
          <td>&nbsp;</td>
        </tr>
        <tr>
          <td><a href="tel:4804149116">phone</a></td>
          <td>
            <a href="https://www.linkedin.com/in/rebekah-willis-906824235/" target="_blank">
              linkedin
            </a>
          </td>
        </tr>
      </table>
    </div>
  </div>
  <footer class="footer" style="color: rgb(162, 167, 171);">
    Buona Giornata!
  </footer>
</body>
<script src="{% static 'recipes/js/navigation.js' %}"></script>

</html>

src/recipes/templates/recipes/add_recipe.html
{% load static %}

<!DOCTYPE html>
<html lang="en">

<head>
  <meta charset="UTF-8">
  <meta name="viewport" content="width=device-width, initial-scale=1.0">
  <link rel="stylesheet" type="text/css" href="{% static 'recipes/css/search.css' %}">
  <title>Add a Recipe</title>
</head>

<body>
  <h1><a href="{% url 'recipes:list' %}">Add a Recipe</a></h1>
  <br>
  <div class="navigation">
    <button onclick="showMenu()" class="navigation">
      <img src="{% static 'recipes/images/recipe.jpg' %}" width="26px" />
    </button>
    <div id="nav" class="hide">
      <ul>
        <a href="{% url 'recipes:list' %}">
          <li>home</li>
        </a>
        <a href="{% url 'recipes:search' %}">
          <li>search</li>
        </a>
        <a href="{% url 'recipes:about' %}">
          <li>about</li>
        </a>
        <a href="{% url 'logout' %}">
          <li>logout</li>
        </a>
      </ul>
    </div>
  </div>
  <div class="add_card">
    <form action="" method="POST" enctype="multipart/form-data">
      {% csrf_token %}
      <table cellpadding="0" cellspacing="0">
        <tr>
          <th>Recipe Name</th>
          <td>{{form.name}}</td>
        </tr>
        <tr>
          <th>{{form.cooking_time.label}}</th>
          <td>{{form.cooking_time}}</td>
        </tr>
        <tr>
          <th>{{form.ingredients.label}}</th>
          <td>{{form.ingredients}}</td>
        </tr>
        <tr>
          <th>recipe image</th>
          <td>{{form.pic}}</td>
        </tr>
      </table>
      <br><br>
      <button type="submit">
        ADD RECIPE
      </button>
    </form>
  </div>
  <div class="footer">
    <span class="text">This App was created by Rebekah Willis. 
      <a
        href="https://github.com/rbkh17willis">
        My Github Here</a>
    </span>
  </div>
</body>
<script src="{% static 'recipes/js/navigation.js' %}"></script>

</html>

src/recipes/templates/recipes/recipe_detail.html
{% load static %}

<!DOCTYPE html>
<html lang="en">

<head>
  <meta charset="UTF-8">
  <meta name="viewport" content="width=device-width, initial-scale=1.0">
  <link rel="stylesheet" type="text/css" href="{% static 'recipes/css/recipes.css' %}">
  <title>{{object.name}}</title>
</head>

<body>
  {% if messages %}
  {% for message in messages %}
  <div style="text-align: center;" class="recipe_time" id="message">
    {{message}}
    <button onclick="dismiss()">
      dismiss
    </button>
  </div>
  {% endfor %}
  {% endif %}
  <h1>{{object.name.lower}}
    <br>
    <button id="update-button" onclick="updateDialog()">update</button>
    <button id="delete-button" onclick="deleteDialog()">delete</button>
  </h1>
  <div class="navigation">
    <button onclick="showMenu()" class="navigation">
      <img src="{% static 'recipes/images/recipe.jpg' %}" width="26px" />
    </button>
    <div id="nav" class="hide">
      <ul>
        <a href="{% url 'recipes:list' %}">
          <li>home</li>
        </a>
        <a href="{% url 'recipes:search' %}">
          <li>search</li>
        </a>
        <a href="{% url 'recipes:add' %}">
          <li>add recipe</li>
        </a>
        <a href="{% url 'recipes:about' %}">
          <li>about</li>
        </a>
        <a href="{% url 'logout' %}">
          <li>logout</li>
        </a>
      </ul>
    </div>
  </div>
  <div class="recipe_detail" onclick="closeDialog()">
    <span id="recipe_card">
      <br>
      <a class="goBack" title="Go back" href="{% url 'recipes:list' %}">
        &laquo;
      </a>
      <span class="recipe_info">
        <table class="recipe_info" style="background: none; text-align: left; margin-left: auto; margin-right: auto;"
          cellpadding="5" cellspacing="5">
          <tr>
            <th style="font-style: italic;">
              &nbsp;cooking time
            </th>
            <td>
              {{object.cooking_time}} minutes
            </td>
          </tr>
          <tr>
            <th style="font-style: italic; border-top: dotted 1px black;">
              &nbsp;difficulty lvl
            </th>
            <td>
              {{object.calculate_difficulty}}
            </td>
          </tr>
          <tr>
            <th style="font-style: italic; border-top: dotted 1px black;">
              &nbsp;Ingredients
              {% for len(ing) in object.return_ingredients_as_list %}
              <br>
              {% endfor %}
            </th>
            <td>
              {% for ing in object.return_ingredients_as_list %}
              {{ing}}
              <br>
              {% endfor %}
            </td>
          </tr>
        </table>
      </span>
      <br>
      <div class="image_mask">
        <img src="{{object.pic.url}}" class="helper" />
      </div>
    </span>
  </div>
  <div class="update_detail">
    <span id="update_card" class="hide">
      <span class="recipe_info">
        <form action="{% url 'recipes:update' object.id %}" method="POST" enctype="multipart/form-data">
          {% csrf_token %}
          <table class="recipe_info" style="background: none; text-align: left; margin-left: auto; margin-right: auto;"
            cellpadding="5" cellspacing="5">
            <tr>
              <th style="font-style: italic; border-top: dotted 1px black;">
                &nbsp;Recipe Name
              </th>
              <td>
                {{form.name}}
              </td>
            </tr>
            <tr>
              <th style="font-style: italic;">
                &nbsp;cooking time
              </th>
              <td>
                {{form.cooking_time}}
              </td>
            </tr>
            <tr>
              <th style="font-style: italic; border-top: dotted 1px black;">
                &nbsp;Ingredients
              </th>
              <td>
                {{form.ingredients}}
              </td>
            </tr>
          </table>
          <span>
            {{form.pic}}
            <br><br>
            <button type="submit">
              UPDATE RECIPE
            </button>
            <button type="button" onclick="closeUpdate()">
              close
            </button>
          </span>
        </form>
      </span>
    </span>
  </div>
  <div class="delete_detail">
    <span id="delete_card" class="hide">
      <span class="recipe_info">
        <form action="{% url 'recipes:delete' object.id %}" method="POST" enctype="multipart/form-data">
          {% csrf_token %}
          Delete {{object.name}} from your recipes?
          <br><br>
          <button type="submit" class="danger">
            Yes
          </button>
          <button type="button" onclick="closeDelete()">
            No
          </button>
        </form>
      </span>
    </span>
  </div>
  <div class="footer">
    <span class="text">This App was created by Rebekah Willis. 
      <a
        href="https://github.com/rbkh17willis">
        My Github Here</a>
    </span>
  </div>
</body>
<script src="{% static 'recipes/js/navigation.js' %}"></script>

</html>

src/recipes/templates/recipes/recipe_list.html
{% load static %}

<!DOCTYPE html>
<html lang="en">

<head>
  <meta charset="UTF-8">
  <meta name="viewport" content="width=device-width, initial-scale=1.0">
  <link rel="stylesheet" type="text/css" href="{% static 'recipes/css/recipes.css' %}">
  <title>Recipe List</title>
</head>

<body>
  {% if messages %}
  {% for message in messages %}
  <div style="text-align: center;" class="recipe_time" id="message">
    {{message}}
    <button onclick="dismiss()">
      dismiss
    </button>
  </div>
  {% endfor %}
  {% endif %}
  <h1><a href="{% url 'recipes:list' %}">List of Recipes</a></h1>
  <br>
  <div class="navigation">
    <button onclick="showMenu()" class="navigation">
      <img src="{% static 'recipes/images/recipe.jpg' %}" width="26px" />
    </button>
    <div id="nav" class="hide">
      <ul>
        <a href="{% url 'recipes:search' %}">
          <li>search</li>
        </a>
        <a href="{% url 'recipes:add' %}">
          <li>add recipe</li>
        </a>
        <a href="{% url 'recipes:about' %}">
          <li>about</li>
        </a>
        <a href="{% url 'logout' %}">
          <li>logout</li>
        </a>
      </ul>
    </div>
  </div>

  {% for object in object_list %}
  <div class="recipe_list">
    <span class="recipe_cards">
      <span class="recipe_name">
        <a href="{{object.get_absolute_url}}">{{object.name.title}}</a>
      </span>
      <br>
      <span class="recipe_time">{{object.cooking_time}} minutes</span>
      <br><br>
      <div class="image_mask">
        <img src="{{object.pic.url}}" class="helper" />
      </div>
    </span>
  </div>
  {% endfor %}
  <div class="footer">
    <span class="text">This App was created by Rebekah Willis. 
      <a
        href="https://github.com/rbkh17willis">
        My Github Here</a>
    </span>
  </div>
</body>
<script src="{% static 'recipes/js/navigation.js' %}"></script>

</html>

src/recipes/templates/recipes/recipe_search.html
{% load static %}

<!DOCTYPE html>
<html lang="en">

<head>
  <meta charset="UTF-8">
  <meta name="viewport" content="width=device-width, initial-scale=1.0">
  <link rel="stylesheet" type="text/css" href="{% static 'recipes/css/search.css' %}">
  <title>Search</title>
</head>

<body>
  <h1>
    <a href="{% url 'recipes:list' %}">Search Recipe App</a>
  </h1>
  <br>
  <div class="navigation">
    <button onclick="showMenu()" class="navigation">
      <img src="{% static 'recipes/images/recipe.jpg' %}" width="26px" />
    </button>
    <div id="nav" class="hide">
      <ul>
        <a href="{% url 'recipes:list' %}">
          <li>home</li>
        </a>
        <a href="{% url 'recipes:add' %}">
          <li>add recipe</li>
        </a>
        <a href="{% url 'recipes:about' %}">
          <li>about</li>
        </a>
        <a href="{% url 'logout' %}">
          <li>logout</li>
        </a>
      </ul>
    </div>
  </div>

  <div class="search_card">
    <form action="" method="POST">
      {% csrf_token %}
      {{form.recipe_search.label}} <br><br> {{form.recipe_search}}
      <br><br>
      {{form.chart_type}}
      <br><br><br>
      <button type="submit">
        Search
      </button>
    </form>
  </div>

  <br>

  <div class="search_card">
    {% if recipes_df %}
    <table class="recipe_info" cellpadding="0" cellspacing="0">
      <tr>
        <th>
          Recipe
        </th>
        <th>
          Ingredients
        </th>
        <th style="width: 25%;">
          Time
        </th>
      </tr>
      {% for recipe in qs %}
      <tr>
        <td><a href="{{recipe.get_absolute_url}}">{{recipe.name}}</a></td>
        <td>{{recipe.ingredients}}</td>
        <td>{{recipe.cooking_time}}</td>
      </tr>
      {% endfor %}
    </table>
    <br>
    <img src=" data:image/png;base64, {{chart|safe}}" width="80%" />
    {% else %}
    <h3>no data yet</h3>
    {% endif %}
  </div>
  <div class="footer">
    <span class="text">This App was created by Rebekah Willis. 
      <a
        href="https://github.com/rbkh17willis">
        My Github Here</a>
    </span>
  </div>
</body>
<script src="{% static 'recipes/js/navigation.js' %}"></script>

</html>